# Generated by Django 5.1.2 on 2024-10-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mbti', models.CharField(max_length=4)),
                ('affiliations', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('participation_field', models.CharField(choices=[('frontend', '프론트엔드'), ('backend', '백엔드'), ('planning', '기획'), ('design', '디자인')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.CharField(max_length=100)),
            ],
        ),
    ]
