# Generated by Django 5.1.2 on 2024-11-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_profile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="teams.team",
            ),
            preserve_default=False,
        ),
    ]
