# Generated by Django 5.1.2 on 2024-11-01 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
