# Generated by Django 5.1.2 on 2024-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_alter_team_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
