# Generated by Django 5.1.2 on 2024-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0005_alter_profile_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
        migrations.AddField(
            model_name="profile",
            name="collaboration_environment",
            field=models.IntegerField(
                choices=[(1, "오프라인 모임"), (2, "온라인 모임")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="communication_style",
            field=models.IntegerField(
                choices=[(1, "주기적 회의"), (2, "필요할 때만 연락")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="editor_mode",
            field=models.IntegerField(choices=[(1, "라이트 모드"), (2, "다크 모드")], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="focus_time",
            field=models.IntegerField(choices=[(1, "아침"), (2, "야간")], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="github_address",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_os",
            field=models.IntegerField(
                choices=[(1, "Windows"), (2, "MacOS")], default=11
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="project_style",
            field=models.IntegerField(choices=[(1, "계획적"), (2, "즉흥적")], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="stack",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_environment",
            field=models.IntegerField(
                choices=[(1, "조용한 환경"), (2, "시끌시끌한 카페")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mbti",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
