# Generated by Django 5.1.2 on 2024-11-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0006_remove_profile_age_profile_collaboration_environment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("team_leader", "팀장"), ("team_member", "팀원")],
                default="team_member",
                max_length=20,
            ),
        ),
    ]
