# Generated by Django 5.1.2 on 2024-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0009_team_goals_team_rules_profilequestionanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="collaboration_environment",
            field=models.IntegerField(
                choices=[(1, "오프라인 모임"), (2, "온라인 모임")], default=1
            ),
        ),
    ]
