# Generated by Django 5.1.2 on 2024-11-02 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0013_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
