# Generated by Django 5.1.2 on 2024-11-02 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0014_remove_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilequestionanswer",
            name="team",
            field=models.ForeignKey(
                default=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
            preserve_default=False,
        ),
    ]
